---
title: "cross_validation"
author: "Wenshan Qu (wq2160)"
date: "11/16/2021"
output: github_document
---

```{r}

library(tidyverse)
library(viridis)

library(modelr)
library(mgcv) ## For fitting nonlinear models

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Simulate a dataset

```{r}
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point()

```


## Create splits by hand; plot; fit some models

```{r}
train_df = sample_n(nonlin_df, 80)
## test data should not in the trainning data
test_df = anti_join(nonlin_df, train_df, by = "id")

ggplot(train_df, aes(x = x, y = y)) +
  geom_point() +
  geom_point(data = test_df, color = "red")
```

Fit my model:

```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = mgcv::gam(y ~ s(x), data = train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df) ## more complex
```

Plot the results

```{r}
train_df %>% 
  add_predictions(smooth_mod) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  geom_line(aes(y = pred))

train_df %>% ## putting to much stuff in my model!! Not good!
  add_predictions(wiggly_mod) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  geom_line(aes(y = pred))

train_df %>% ## putting to little things in my model!! Not good!
  add_predictions(linear_mod) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  geom_line(aes(y = pred))
```

Quantify the results

```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

## CV iteratively

use `modelr::crossv_mc`

```{r}
cv_df = 
   crossv_mc(nonlin_df, 100) ## train 100 times

## let's check!
cv_df %>%  pull(train) %>% .[[1]] %>%  as_tibble() ## `[[1]]` means give me the first element in the list.

## continue ...
cv_df = 
   crossv_mc(nonlin_df, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```

Let's fit some models

```{r}
cv_df %>% 
  mutate(
    linear_mod = map(.x = train, ~lm(y ~ x, data = .x))
  ) %>% 
  mutate(
    rsme_linear = map2_dbl(.x = linear_mod, .y = test, ~rmse(model = .x, data = .y)) ## `dbl` could give us number version.
  )
```

```{r}
cv_df = 
  cv_df %>% 
    mutate(
      linear_mod = map(.x = train, ~lm(y ~ x, data = .x)),
      smooth_mod = map(.x = train, ~gam(y ~ s(x), data = .x)),
      wiggly_mod = map(.x = train, ~gam(y ~ s(x, k = 30), sp = 10e-6, data = .x))
    ) %>% 
    mutate(
      rmse_linear = map2_dbl(.x = linear_mod, .y = test, ~rmse(model = .x, data = .y)),
      rmse_smooth = map2_dbl(.x = smooth_mod, .y = test, ~rmse(model = .x, data = .y)),
      rmse_wiggly = map2_dbl(.x = wiggly_mod, .y = test, ~rmse(model = .x, data = .y))
    )

```

look at output

```{r}
cv_df %>% 
  select(.id, starts_with("rmse")) %>% 
  pivot_longer(
    rmse_linear:rmse_wiggly,
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) %>% 
  ggplot(aes(x = model, y = rmse)) +
  geom_point()
```


## Child growth

```{r}
child_growth = 
  read_csv("./nepalese_children.csv")
```

```{r}
child_growth %>% 
  ggplot(aes(x = weight, y = armc)) +
  geom_point(alpha = .2)
```

Consider candidate models

```{r}
child_growth = 
  read_csv("./nepalese_children.csv") %>% 
  mutate(
    weight_cp = (weight > 7) * (weight - 7) ## this is for pwl_mod
    ## we choose 7 as the change point
  )
```


```{r}
linear_mod = lm(armc ~ weight, data = child_growth)
pwl_mod = lm(armc ~ weight + weight_cp, data = child_growth) ## piece wise linear model?
smooth_mod = gam(armc ~ s(weight), data = child_growth)
```

```{r}
child_growth %>% 
  add_predictions(pwl_mod) %>% 
  ggplot(aes(x = weight, y = armc)) +
  geom_point(alpha = .2) +
  geom_line(aes(y = pred), color = "red")
```

Use CV to compare models.
```{r}
cv_df =
  crossv_mc(child_growth, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

Fit models and extract RMSE
```{r}
cv_df = 
  cv_df %>% 
  mutate(
    linear_mod  = map(train, ~lm(armc ~ weight, data = .x)),
    pwl_mod     = map(train, ~lm(armc ~ weight + weight_cp, data = .x)),
    smooth_mod  = map(train, ~gam(armc ~ s(weight), data = as_tibble(.x)))) %>% 
  mutate(
    rmse_linear = map2_dbl(linear_mod, test, ~rmse(model = .x, data = .y)),
    rmse_pwl    = map2_dbl(pwl_mod,    test, ~rmse(model = .x, data = .y)),
    rmse_smooth = map2_dbl(smooth_mod, test, ~rmse(model = .x, data = .y)))
```

```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin()
```

linear model is missing important values, do not enough.